stages:
  - build

.build:
  stage: build
  image: crops/poky
  before_script:
    - export PATH=~/.local/bin:$PATH
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - python3 -m pip install kas
    - wget -q 'https://downloads.rclone.org/rclone-current-linux-amd64.zip'
    - unzip -q rclone-current-linux-amd64.zip
    - mv rclone-*-linux-amd64/rclone ~/.local/bin/
    - rm -rf rclone-*-linux-amd64*
  after_script:
    - rm -rf build
    - ./scripts/ci-cleanup.sh
  cache:
    paths:
      - layers

qemux86:
  extends: .build
  script:
  - kas build --target security-build-image kas/$CI_JOB_NAME.yml 

qemux86-64:
  extends: .build
  script:
  - kas build --target security-build-image kas/$CI_JOB_NAME.yml 

qemuarm:
  extends: .build
  script:
  - kas build --target security-build-image kas/$CI_JOB_NAME.yml 

qemuarm64:
  extends: .build
  script:
  - kas build --target security-build-image kas/$CI_JOB_NAME.yml 

qemuppc:
  extends: .build
  script:
  - kas build --target security-build-image kas/$CI_JOB_NAME.yml 

qemumips64:
  extends: .build
  script:
  - kas build --target security-build-image kas/$CI_JOB_NAME.yml 

qemuriscv64:
  extends: .build
  script:
  - kas build --target security-build-image kas/$CI_JOB_NAME.yml 

qemux86-64-tpm:
  extends: .build
  script:
  - kas build --target security-tpm-image kas/$CI_JOB_NAME.yml 

qemux86-64-tpm2:
  extends: .build
  script:
  - kas build --target security-tpm2-image kas/$CI_JOB_NAME.yml 

qemuarm64-tpm2:
  extends: .build
  script:
  - kas build --target security-tpm2-image kas/$CI_JOB_NAME.yml 

qemux86-ima:
  extends: .build
  script:
  - kas build --target integrity-image-minimal kas/$CI_JOB_NAME.yml 

qemux86-64-ima:
  extends: .build
  script:
  - kas build --target integrity-image-minimal kas/$CI_JOB_NAME.yml 

qemuarm64-ima:
  extends: .build
  script:
  - kas build --target integrity-image-minimal kas/$CI_JOB_NAME.yml 
